### ISSUE TITLE
Module32First() 执行失败

### ISSUE THREAD

**Issue by 0xabcdefff** [A2kaid/Get-WeChat-DB#1]
Getkey.cpp line 34 	
BOOL bRet = ::Module32First(hModuleSnap, &me32);
并不能正确执行

**Comment by 0xabcdefff** [comment]
不能编译为x64

**Comment by A2kaid** [comment]
对，主要CreateToolhelp32Snapshot函数不能正确获取64位进程基址，需要换种方法才能编译成64位程序，64位进程可以枚举32位进程的模块，但32位进程不可以枚举64位进程的模块，主要微信是32位的程序。。。。
