### ISSUE TITLE
哈哈，你把我想要实现的功能实现了。

### ISSUE THREAD

**Issue by Vxer-Lee** [A2kaid/Get-WeChat-DB#3]
不过这个不匹配所有的微信版本，如果匹配所有微信版本，其实有一种特征码匹配的方法，具体搜一下吾爱破解里面的LOL特征码定位文章，开启新大陆。

**Comment by A2kaid** [comment]
好的，我去学习下

**Comment by Vxer-Lee** [comment]
https://www.52pojie.cn/thread-282441-1-1.html 是这篇文章，大佬要不要弄个PC逆向群交流
