### ISSUE TITLE
能收到文件，但是是收到两个文件，一个是dec_MSG0一个是MicroMsg但是似乎两个都需要密码才能打开

### ISSUE THREAD

**Issue by wuyoukm** [A2kaid/Get-WeChat-DB#5]
能收到文件，但是是收到两个文件，一个是dec_MSG0一个是MicroMsg但是似乎两个都需要密码才能打开，我尝试了发送过来的密钥也打不开两个文件，
![image](https://user-images.githubusercontent.com/28343933/95998050-0c8e3a00-0e67-11eb-93ba-9ec77f2ecbb9.png)

微信版本2.9.556

**Comment by A2kaid** [comment]
dec_MSG0 是解密MicroMsg得到的，正常是可以直接打开，应该是密钥错误了，32个字节的密钥里末尾不会有那么多00填充，密钥获取错误可能是client这边读取微信内存有问题，可以检查下微信的版本和密钥的位置是否正确，方法参考这篇文章：https://blog.csdn.net/qq_38474570/article/details/96606530

**Comment by wuyoukm** [comment]
我2.9.556 版本微信 装在 2008上了 我换成 win7 或者 win10  测试一下 2.9.556 版本

**Comment by wuyoukm** [comment]
win10 上 测试 没问题，但是，为啥数据库里面 找不到完整的聊天记录，大佬给连接里面的文章是Chatmsg，但是大佬的是Micromsg 和这个有关系吗

**Comment by A2kaid** [comment]
微信的数据库很多，用的同一个密钥，你可以改改代码，完整聊天记录应该在Msg\Multi那个文件夹里，名字是MSG0.db，但是解密数据库的脚本有点bug，太大的文件只能解一部分

**Comment by wuyoukm** [comment]
我能获取密钥后，直接用密钥打开原始数据库文件吗？

**Comment by A2kaid** [comment]
可以，但必须是你获取密钥的那台电脑上的微信数据库

**Comment by wuyoukm** [comment]
大佬你看吐司私信，我给你私信了，加个扣扣或者微信交流一下呗
